import 'package:flutter/material.dart';

import '../../l10n/generated/app_localizations.dart';

class TermsScreen extends StatelessWidget {
  const TermsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final l = AppLocalizations.of(context);
    final theme = Theme.of(context);
    final locale = Localizations.localeOf(context).languageCode;
    final body = locale == 'ja' ? _bodyJa : _bodyEn;
    final lastUpdated = locale == 'ja'
        ? '最終更新: 2026年5月26日'
        : 'Last updated: May 26, 2026';

    return Scaffold(
      appBar: AppBar(title: Text(l.settingsTerms)),
      body: ListView(
        padding: EdgeInsets.fromLTRB(
          20,
          16,
          20,
          32 + MediaQuery.viewPaddingOf(context).bottom,
        ),
        children: [
          Text(lastUpdated, style: theme.textTheme.bodySmall),
          const SizedBox(height: 16),
          Text(
            body,
            style: theme.textTheme.bodyMedium?.copyWith(height: 1.7),
          ),
        ],
      ),
    );
  }
}

const _bodyJa = '''
本規約は、AIジャーナル（以下「本アプリ」）のご利用条件を定めるものです。本アプリをご利用いただくことで、本規約に同意したものとみなします。

## 1. ご利用について

本アプリは、個人のライフログ・日記作成を目的としたサービスです。本アプリは「現状のまま」提供され、運営者は本アプリの完全性、正確性、特定目的への適合性について保証しません。

## 2. データ管理の責任

本アプリの設計上、すべての日記データはユーザーの端末内（または、ユーザー自身が指定したクラウドフォルダ）に保管されます。運営者はユーザーのデータをサーバー上に保管しないため、端末紛失・故障・データ削除・クラウド設定ミス等によるデータ消失について、運営者は責任を負いません。
重要なデータは、必ずユーザーご自身でバックアップを取ってください。

## 3. AI生成コンテンツについて

本アプリが生成する日記本文・要約・フィードバックは、AI（Gemini API等）が機械的に生成したものであり、必ずしも事実や意図と一致しない場合があります。生成された内容は、ご自身の責任でご確認・編集してください。

## 4. 課金プランについて

有料プランは、各プラットフォーム（App Store / Google Play）の課金システムを通じて提供されます。返金・キャンセル等の取り扱いは、各プラットフォームのポリシーに従います。

初回特典（10回無料体験）や招待コードによる特典は、運営者の裁量により変更・終了する場合があります。

## 5. 禁止事項

本アプリのご利用にあたり、以下の行為を禁止します。
- 法令または公序良俗に違反する行為
- 本アプリの運営を妨害する行為
- リバースエンジニアリング、解析、改変等の行為
- 招待コードの不正取得・転売

## 6. サービスの変更・終了

運営者は、ユーザーへの事前通知なく、本アプリの全部または一部の機能を変更・終了する場合があります。

## 7. 規約の変更

本規約は、運営者が必要と判断した際に変更される場合があります。変更後の規約は、本アプリ内に掲載した時点で効力を生じます。

## 8. 準拠法・裁判管轄

本規約の解釈には日本法を適用し、本アプリに関する紛争については東京地方裁判所を第一審の専属的合意管轄裁判所とします。
''';

const _bodyEn = '''
These Terms govern your use of AI Journal ("the App"). By using the App, you agree to be bound by these Terms.

## 1. Use of the App

The App is provided as a personal life-logging and journaling service. It is provided "as is", and the operators make no warranty regarding its completeness, accuracy, or fitness for any particular purpose.

## 2. Data responsibility

By design, all your diary data is stored on your device (or in a cloud folder you choose). The operators do not store your data on a server. The operators are not liable for data loss caused by device loss, hardware failure, accidental deletion, cloud-sync misconfiguration, or similar.
Please back up important data yourself.

## 3. AI-generated content

Diary text, summaries, and feedback generated by the App are produced by AI (e.g. Gemini API) and may not align with the facts or your intent. Please review and edit generated content at your own discretion.

## 4. Paid plans

Paid plans are sold via the platform's in-app purchase system (App Store / Google Play). Refunds, cancellations, and similar are handled per each platform's policy.

The 10-entry free trial and benefits from invite codes may be modified or discontinued at the operators' discretion.

## 5. Prohibited conduct

You may not:
- Use the App in violation of law or public morals
- Interfere with the App's operation
- Reverse-engineer, decompile, or modify the App
- Fraudulently obtain or resell invite codes

## 6. Changes / discontinuation

The operators may change or discontinue any part of the App without prior notice.

## 7. Changes to these Terms

These Terms may be updated when the operators deem necessary. Updated Terms take effect upon being posted in the App.

## 8. Governing law

These Terms are governed by Japanese law. The Tokyo District Court shall have exclusive jurisdiction for the first instance over any dispute arising from the App.
''';
